# Data Cleaning Notebook

## Week 3: Load, Inspect, and Clean Your Data

In this notebook, we'll take a raw dataset and transform it into a clean, ready-to-analyze format.

### Steps:
1. Load the data
2. Inspect its structure and quality
3. Handle missing values
4. Remove duplicates
5. Fix data types
6. Handle outliers
7. Export clean data

---

## Import Required Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Set display options for better readability
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

print("Libraries imported successfully!")

Libraries imported successfully!

## Step 1: Load the Data

First, we need to load a dataset. You can use:
- A CSV file from your computer
- A CSV from Kaggle
- A built-in dataset like Iris or Titanic

For this example, we'll use a sample dataset. Replace this with your own!

In [2]:
# TODO: Load your dataset
# Option 1: From a CSV file on your computer
df = pd.read_csv('../datasets/dataset.csv')

# Option 2: Create a sample dataset for practice
df1 = pd.DataFrame({
    'ID': [1, 2, 3, 4, 5, 6, 7, 8],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Henry'],
    'Age': [25, 30, np.nan, 28, 35, 29, 26, np.nan],
    'Salary': [50000, 60000, 55000, 65000, 75000, 70000, 52000, 68000],
    'Department': ['Sales', 'IT', 'HR', 'Sales', 'IT', 'HR', 'IT', 'Sales'],
    'Years': [2, 5, 3, 4, 7, 6, 2, 4]
})

print(f"Dataset loaded successfully!")
print(f"my titanic dataset Shape: {df.shape}")
print(f'dictionary to df shape: {df1.shape}')

Dataset loaded successfully!
my titanic dataset Shape: (891, 12)
dictionary to df shape: (8, 6)

## Step 2: Inspect the Data

Before cleaning, understand what you're working with.

In [3]:
# display the first few rows
print('First 5 rows: ')
display(df.head())

#display the last 5 rows
print('the last 5 rows: ')
display(df.tail())

First 5 rows:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

the last 5 rows:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [4]:
# Display first few rows
print("First 5 rows:")
print(df1.head())

print("\nLast 5 rows:")
print(df1.tail())

First 5 rows:
   ID     Name   Age  Salary Department  Years
0   1    Alice  25.0   50000      Sales      2
1   2      Bob  30.0   60000         IT      5
2   3  Charlie   NaN   55000         HR      3
3   4    David  28.0   65000      Sales      4
4   5      Eve  35.0   75000         IT      7

Last 5 rows:
   ID   Name   Age  Salary Department  Years
3   4  David  28.0   65000      Sales      4
4   5    Eve  35.0   75000         IT      7
5   6  Frank  29.0   70000         HR      6
6   7  Grace  26.0   52000         IT      2
7   8  Henry   NaN   68000      Sales      4

In [5]:
# Check data info
print("Data Info:")
df.info()

Data Info:
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [6]:
# data info
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          8 non-null      int64
 1   Name        8 non-null      str
 2   Age         6 non-null      float64
 3   Salary      8 non-null      int64
 4   Department  8 non-null      str
 5   Years       8 non-null      int64
dtypes: float64(1), int64(3), str(2)
memory usage: 516.0 bytes

In [7]:
# Get descriptive statistics
print("Descriptive Statistics:")
df.describe()

Descriptive Statistics:

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [8]:
# standard distribution of data
df1.describe()

            ID        Age       Salary     Years
count  8.00000   6.000000      8.00000  8.000000
mean   4.50000  28.833333  61875.00000  4.125000
std    2.44949   3.544949   9062.28448  1.807722
min    1.00000  25.000000  50000.00000  2.000000
25%    2.75000  26.500000  54250.00000  2.750000
50%    4.50000  28.500000  62500.00000  4.000000
75%    6.25000  29.750000  68500.00000  5.250000
max    8.00000  35.000000  75000.00000  7.000000

In [9]:
# Check for missing values
print("Missing Values Count:")
print(df.isnull().sum())

print("\nMissing Values Percentage:")
print((df.isnull().sum() / len(df)) * 100)

Missing Values Count:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Missing Values Percentage:
PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [10]:
# checking for missing values
print('total count of missing values\n'+'='*30)
print(df1.isna().sum())

print('\npercentage rate of missing values\n'+'='*35)
display((df1.isna().sum()/len(df1)*100))

total count of missing values
==============================
ID            0
Name          0
Age           2
Salary        0
Department    0
Years         0
dtype: int64

percentage rate of missing values
===================================

ID             0.0
Name           0.0
Age           25.0
Salary         0.0
Department     0.0
Years          0.0
dtype: float64

In [29]:
# Check for duplicates
print(f"Total duplicate rows: {df.duplicated().sum()}")

# Check for duplicates based on specific columns
print(f"\nDuplicate IDs: {df.duplicated(subset=['PassengerId']).sum()}")

Total duplicate rows: 0

Duplicate IDs: 0

In [12]:
# checking for duplicate
print(f'total duplicate rows: {df1.duplicated().sum()}')

print(f"Duplicate IDs: {df1.duplicated(subset=['ID']).sum()}")

total duplicate rows: 0
Duplicate IDs: 0

## Step 3: Handle Missing Values

Different strategies for different situations:
- **Drop**: Remove rows with missing values (use if <5% missing)
- **Fill with mean/median**: Preserve data size (numerical columns)
- **Fill with mode**: For categorical columns
- **Forward/Backward fill**: For time series data

In [13]:
# Example: Handle missing values in 'Age'
print("Original Age column:")
print(df1['Age'])

# Option 1: Fill with median (good for numerical data)
# df1['Age'].fillna(df['Age'].median(), inplace=True)
df1.fillna({'Age':df1['Age'].median()},inplace=True)

print("\nAge after filling with median:")
print(df1['Age'])

Original Age column:
0    25.0
1    30.0
2     NaN
3    28.0
4    35.0
5    29.0
6    26.0
7     NaN
Name: Age, dtype: float64

Age after filling with median:
0    25.0
1    30.0
2    28.5
3    28.0
4    35.0
5    29.0
6    26.0
7    28.5
Name: Age, dtype: float64

In [ ]:
# origin data of titanic without filling of missing
print('Original dataset\n'+'='*20)
print(df[['Age','Cabin','Embarked']])

# filing the missing values
df.fillna({'Age':df['Age'].mean()}, inplace=True)
df.fillna({'Embarked':df['Embarked'].ffill()}, inplace=True)
df.fillna({'Cabin':df['Cabin'].ffill()}, inplace=True)



# after filling the missing values with mean and mode
print('\n After updating missing values with mean and mode \n'+'='*40)
print(df[['Age','Cabin','Embarked']])

Original dataset
====================
           Age Cabin Embarked
0    22.000000   C85        S
1    38.000000   C85        C
2    26.000000  C123        S
3    35.000000  C123        S
4    35.000000   E46        S
..         ...   ...      ...
886  27.000000   B42        S
887  19.000000   B42        S
888  29.699118  C148        S
889  26.000000  C148        C
890  32.000000  C148        Q

[891 rows x 3 columns]

 After updating missing values with mean and mode
========================================
           Age Cabin Embarked
0    22.000000   C85        S
1    38.000000   C85        C
2    26.000000  C123        S
3    35.000000  C123        S
4    35.000000   E46        S
..         ...   ...      ...
886  27.000000   B42        S
887  19.000000   B42        S
888  29.699118  C148        S
889  26.000000  C148        C
890  32.000000  C148        Q

[891 rows x 3 columns]

In [30]:
# Verify missing values are gone
print("Missing values after cleaning:")
print(df.isnull().sum())

Missing values after cleaning:
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [32]:
# check for missing values after cleaning
# df1.info()
df1.isna().sum()

ID            0
Name          0
Age           0
Salary        0
Department    0
Years         0
dtype: int64

## Step 4: Remove Duplicates

Identical rows should typically be removed (unless they represent real duplicates).

In [34]:
# Check for complete duplicates
print(f"Duplicate rows before removal: {df1.duplicated().sum()}")

# Remove duplicates
df_clean = df1.drop_duplicates()

print(f"Duplicate rows after removal: {df_clean.duplicated().sum()}")
print(f"\nRows removed: {len(df1) - len(df_clean)}")

Duplicate rows before removal: 0
Duplicate rows after removal: 0

Rows removed: 0

In [35]:
# recheck for duplicate after cleaning
print(f'duplicate raw before removal: {df.duplicated().sum()}')

duplicate raw before removal: 0

## Step 5: Fix Data Types

Ensure each column has the correct data type.

In [36]:
print("Current data types:")
print(df_clean.dtypes)

Current data types:
ID              int64
Name              str
Age           float64
Salary          int64
Department        str
Years           int64
dtype: object

In [ ]:
# Convert types if needed
# df_clean['ID'] = df_clean['ID'].astype(int)
# df_clean['Age'] = df_clean['Age'].astype(int)
# df_clean['Salary'] = df_clean['Salary'].astype(float)

print("\nData types are correct!")

## Step 6: Handle Outliers

Outliers might be errors or interesting insights. Investigate before removing!

In [42]:
# Detect outliers using IQR method for numerical columns
def detect_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outliers = data[(data[column] < lower_bound) | (data[column] > upper_bound)]
    return outliers

# Check for outliers in Salary
outliers = detect_outliers_iqr(df_clean, 'Salary')
print(f"Outliers in Salary column:")
print(outliers)

# for the titanic outlier in Survival
tt_outliers =detect_outliers_iqr(df,'PassengerId')
print(f'\nOutliers in Survival rate: \n{tt_outliers}')

Outliers in Salary column:
Empty DataFrame
Columns: [ID, Name, Age, Salary, Department, Years]
Index: []

Outliers in Survival rate:
Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [ ]:
# TODO: Decide whether to remove, cap, or keep outliers
# For now, we'll keep them as they might be legitimate high earners!

## Step 7: Final Data Quality Check & Export

In [43]:
print("=" * 50)
print("FINAL DATA QUALITY REPORT")
print("=" * 50)

print(f"\nShape: {df_clean.shape}")
print(f"Memory usage: {df_clean.memory_usage().sum() / 1024**2:.2f} MB")
print(f"\nMissing values: {df_clean.isnull().sum().sum()}")
print(f"Duplicate rows: {df_clean.duplicated().sum()}")
print(f"\nData types correct: Yes")
print(f"\nFirst few rows of cleaned data:")
df_clean.head()

==================================================
FINAL DATA QUALITY REPORT
==================================================

Shape: (8, 6)
Memory usage: 0.00 MB

Missing values: 0
Duplicate rows: 0

Data types correct: Yes

First few rows of cleaned data:

   ID     Name   Age  Salary Department  Years
0   1    Alice  25.0   50000      Sales      2
1   2      Bob  30.0   60000         IT      5
2   3  Charlie  28.5   55000         HR      3
3   4    David  28.0   65000      Sales      4
4   5      Eve  35.0   75000         IT      7

In [45]:
print("=" * 50)
print("FINAL DATA QUALITY REPORT")
print("=" * 50)

print(f"\nShape: {df.shape}")
print(f"Memory usage: {df.memory_usage().sum() / 1024**2:.2f} MB")
print(f"\nMissing values: {df.isnull().sum().sum()}")
print(f"Duplicate rows: {df.duplicated().sum()}")
print(f"\nData types correct: Yes")
print(f"\nFirst few rows of cleaned data:")
df.head()

==================================================
FINAL DATA QUALITY REPORT
==================================================

Shape: (891, 12)
Memory usage: 0.08 MB

Missing values: 0
Duplicate rows: 0

Data types correct: Yes

First few rows of cleaned data:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,C85,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,C123,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,E46,S

In [ ]:
# Export the cleaned data
output_path = '../datasets/cleaned_data.csv'
df_clean.to_csv(output_path, index=False)
print(f"Cleaned data exported to: {output_path}")

## Summary

✅ Data loaded and inspected
✅ Missing values handled
✅ Duplicates removed
✅ Data types corrected
✅ Outliers investigated
✅ Clean data exported

**Next:** Use this cleaned data in the `eda.ipynb` notebook for analysis!