In [1]:
import pandas as pd
import numpy as np
from scipy import stats
import sqlite3
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Set random seed for reproducibility [1]
np.random.seed(42)

# ============================================
# 1. DATABASE ENGINE SETUP (SQL)
# ============================================
# Create an in-memory database engine
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# Create Tables as defined in the sources [2, 3]
cursor.execute('''
CREATE TABLE employees (
    employee_id INT PRIMARY KEY,
    name VARCHAR(100),
    department VARCHAR(50),
    salary INT,
    years_experience INT
)''')

# Insert sample data from the SQL exercises [3]
employees_data = [
    (1, 'Alice Johnson', 'Sales', 60000, 5),
    (2, 'Bob Smith', 'IT', 75000, 7),
    (3, 'Charlie Brown', 'HR', 55000, 3),
    (4, 'Diana Prince', 'Sales', 65000, 6),
    (5, 'Eve Wilson', 'IT', 80000, 10)
]
cursor.executemany('INSERT INTO employees VALUES (?,?,?,?,?)', employees_data)

In [3]:
# 1. Send the query to the database
cursor.execute("SELECT * FROM employees WHERE department = 'IT'")

# 2. Grab the results
it_employees = cursor.fetchall()

# 3. Print the results to the screen
for employee in it_employees:
    print(employee)

(2, 'Bob Smith', 'IT', 75000, 7)
(5, 'Eve Wilson', 'IT', 80000, 10)

In [4]:
data=pd.read_sql_query(''' Select  * from employees ''',conn)

df_data=pd.DataFrame(data)

In [5]:
df_data.head()

   employee_id           name department  salary  years_experience
0            1  Alice Johnson      Sales   60000                 5
1            2      Bob Smith         IT   75000                 7
2            3  Charlie Brown         HR   55000                 3
3            4   Diana Prince      Sales   65000                 6
4            5     Eve Wilson         IT   80000                10

In [6]:
df=df_data[df_data.salary>60000]
df

   employee_id          name department  salary  years_experience
1            2     Bob Smith         IT   75000                 7
3            4  Diana Prince      Sales   65000                 6
4            5    Eve Wilson         IT   80000                10